### ISSUE TITLE
Issues with Beamforming observations and Track Command

### ISSUE THREAD

**Issue by chhabrasherry** [ovro-lwa/lwa-issues#160]
We followed the system use recipe to start the x engine. Issued the track command and started the new terminal to issue the recording command:
1. The log showed 50.7% right after starting the x_engine. This loss was reported to be 45.5 % last week (04/10/2022). Additionally, the log shows a “queue size: 1” before we tried to start recording the data. The same queue also appeared in the previous Ood's log. We did not know how to check when the previous recording command was queued and how to abort it.
** a screenshot of the log is attached**
2. The second terminal requires rerunning the con.start_xengine_bf(track=True) command before recording can be started. This is an additional step that was not required on gpu09.
3. We see 2 logs for the same date, namely: dr-beam-1.lwacalim01.log.2022-10-09 and dr-beam-2.lwacalim01.log.2022-10-09. We did not submit any commands that should start beam 2.

**Issues with the Track command:**
1. The track command requests a target, even though the default=None is supposed to go to ‘zenith’ automatically. We tried rerunning it with target = ‘zenith’, but that was not actually a recognized target to track.
2. The documentation is inaccurate regarding the target’s coordinates. Is it RA, DEC or Alt, Az? If RA DEC, what units are accepted for RA?
<img width="1441" alt="Screen Shot 2022-10-12 at 1 37 10 PM" src="https://user-images.githubusercontent.com/76202104/195412972-230c737d-38b4-4ccc-bd47-2ca09d371986.png">

**Comment by jaycedowell** [comment]
> The log showed 50.7% right after starting the x_engine. This loss was reported to be 45.5 % last week (04/10/2022). Additionally, the log shows a “queue size: 1” before we tried to start recording the data. The same queue also appeared in the previous Ood's log. We did not know how to check when the previous recording command was queued and how to abort it.

I think the lingering "queue size: 1" is a DR problem where old recording commands aren't removed from the queue.  I'll look into it.

> We see 2 logs for the same date, namely: dr-beam-1.lwacalim01.log.2022-10-09 and dr-beam-2.lwacalim01.log.2022-10-09. We did not submit any commands that should start beam 2.

The log files are generated as long as the DR services are running.  They get populated regardless of whether or not a beam is used.

> The track command requests a target, even though the default=None is supposed to go to ‘zenith’ automatically. We tried rerunning it with target = ‘zenith’, but that was not actually a recognized target to track.

I looked at [mn.control.Controller.start_xengine_bf](https://github.com/ovro-lwa/mnc_python/blob/main/mnc/control.py#L192) and, yes, it will not track zenith.  I guess that makes sense since there is nothing to track at zenith because it is a fixed point.  @caseyjlaw  the documentation should probably be updated to reflect that you need a real target to track in order to track.

> The documentation is inaccurate regarding the target’s coordinates. Is it RA, DEC or Alt, Az? If RA DEC, what units are accepted for RA?

Where is this discrepancy at?

**Comment by rh-codebase** [comment]
Maybe 'track' is the wrong command to point a beam at a fixed Az,El but this seems like a worth while requirement. How else can one verify beamwidth/beam shape?

**Comment by jaycedowell** [comment]
Support for alt,az is available through the lower level `xengine_beamformer_control` module but not currently through `start_xengine_bf`.

**Comment by caseyjlaw** [comment]
I've updated the system use recipe and code to clear this up. New syntax is to use the `track` argument to define how the `target` argument is interpreted. If not tracking, target is (az, el), otherwise, it is (ra, dec) or target name.

**Comment by iveydavis** [comment]
> 

Just tried implementing this (tracking the Sun and just pointing at zenith) but something else seems to be broken
![Capture9](https://user-images.githubusercontent.com/29830471/195949018-3fb734cf-72f0-4ef8-9394-7c42931e0524.PNG)
![Capture10](https://user-images.githubusercontent.com/29830471/195949021-e1a15ed3-0328-4432-a3be-d52975c49563.PNG)
This looks like it maybe an unrelated problem-- we were transitioning back to the original etcd server I think. Maybe that could be responsible? I can submit a separate issue related to that since something seems to have affected slow visibilities recording as well.

**Comment by rh-codebase** [comment]
Yes. Please submit the separate issue.

**Comment by jaycedowell** [comment]
@caseyjlaw and I did some work on this. I would like to think that this is resolved.
