### ISSUE TITLE
Lots of "Breaking from packet receive because of so many late packets"

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#258]
in `journalctl`
lots and lots and lots of these
```
Feb 18 00:40:10 lxdlwagpu02 lwa352_start_xeng_etcd_service.py[9711]: Breaking from packet receive because of so many late packets
```
and then
```
Feb 18 00:40:10 lxdlwagpu02 systemd-journald[700]: Suppressed 17103 messages from lwa-xeng-etcd.service
```

**Comment by gregghallinan** [comment]
On Feb 19, 2023 4:51 PM, Yuping Huang ***@***.***> wrote:

in journalctl
lots and lots and lots of these
Feb 18 00:40:10 lxdlwagpu02 lwa352_start_xeng_etcd_service.py[9711]: Breaking from packet receive because of so many late packets

and then
Feb 18 00:40:10 lxdlwagpu02 systemd-journald[700]: Suppressed 17103 messages from lwa-xeng-etcd.service

—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you are subscribed to this thread.Message
 ID: ***@***.***>
