### ISSUE TITLE
prometheus for calim

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#266]
install.

alert on disk space, no heartbeat, etc.

**Comment by kembyct** [comment]
Is there a specific node? I need a little bit more info on #266.
Thanks

**Comment by caseyjlaw** [comment]
Thanks, Kemby.
We'd like to have lwacalimh, lwacalim00 through 10 all in influx/grafana.

**Comment by kembyct** [comment]
You are welcome, Casey
I wonder if there is a SOP (Standard Operating Procedure) I can rely on in order to get it done. I have watched some videos on it, but I want to know if there is a uniform way to set it up on the system.
Thanks

**Comment by rh-codebase** [comment]
@kembyct I'll send you cred. for the redhat customer portal although you might see if you can create your own account by saying you're with caltech. They might have something. Most open source tools have a website with instructions on installation.

**Comment by caseyjlaw** [comment]
Sorry, but I have not done it myself yet. Rick may be the expert on this.

**Comment by caseyjlaw** [comment]
Kemby installed prometheus on cal-im and storage nodes.
Rick to connect to grafana.

**Comment by rh-codebase** [comment]
There's a bit of a disconnect likely due to the richness of the prometheus framework. Only 1 prometheus server is needed and that is already up and running. The server is configured to pull metrics from configured nodes. Those nodes need the node_exporter application running. I'm not sure if different flavors of linux have different names for these. 

@kembyct: The following link looks like it could be used as an SOP for installing the node exporter on Rocky. Likely there's a similar one for Ubuntu. See what you think. 

https://computingforgeeks.com/install-prometheus-node-exporter-rocky-almalinux/

Also found a book which might be helpful.

https://www.oreilly.com/library/view/prometheus-up/9781098131135/

**Comment by kembyct** [comment]
@rh-codebase So you meant I should install the node_exporter on lwacalim machines. I did install it on lwastor01 and lwastor02 once.

**Comment by rh-codebase** [comment]
Should have stated the requirement and not loosely used the term 'prometheus'. The requirement is to use the prometheus framework to collect linux stats from all the LWA nodes. The prometheus server which collects each node's metrics is currently installed and collecting metrics from: lxdlwamcs, lxdlwagpuXX, lxdlwcr, lwastor01 and lwastor02. The rest of the lwastorXX machines and lwacalimXX need installation.

Did the first URL posted earlier look like a good starting point to develop an SOP?

**Comment by kembyct** [comment]
Yes, it does.

**Comment by kembyct** [comment]
The node_exporter has been installed on all lwacalim nodes. It's running and enabled to start at reboot.

**Comment by rh-codebase** [comment]
something is blocking access to port 9100 on the calim hosts. 9100 is the listening port for node_exporter and the prometheus server needs access to it.

**Comment by kembyct** [comment]
I see firewalld service is running on every calim node. Let me know if I should stop it.

**Comment by rh-codebase** [comment]
asking @yupinghuang

**Comment by kembyct** [comment]
@rh-codebase the port 9100 has just been open on every calim node.

**Comment by rh-codebase** [comment]
thanks. grafana is now plotting data for the calim nodes.
