### ISSUE TITLE
Fast visibility scaling

### ISSUE THREAD

**Issue by surajit4444mondal** [ovro-lwa/lwa-issues#501]
It seems that there is a factor of 4 difference between the fast and slow visibility. I have confirmed this using a test-vector test as well. While the predicted visibilities match exactly with the observed ones in case of slow visibilities, the observed fast visibilities were a factor of 4 higher than the predicted ones. The easiest way to explain this factor of 4 is the fact that the number of channels are different between fast and slow vis by exactly factor of 4. The observed fast and slow vis plots will clearly show that the range of slow visibilities is smaller than that for the fast visibilities. Now since this is a constant factor, this can be corrected by combining this in the bandpass calibration step. @binchensun @dgary50 What do you think? Should we bring this up or shall we correct for this in the bandpass correction for fast vis?
![fast_vis_full](https://github.com/ovro-lwa/lwa-issues/assets/70334887/82502ee1-7ea4-4e30-af57-b8a42a392895)
![slow_vis_full](https://github.com/ovro-lwa/lwa-issues/assets/70334887/37b4104c-6e0d-48f3-ae62-ffb475d92e7c)

**Comment by dgary50** [comment]
Good point. I am sure you are right about where the factor comes from.  I would mention it since others may want to use such data. I suppose it could be removed prior to recording, since it will be common practice to apply calibration from slow vis—it is better if there are no “magic” factors to apply. Regards,DaleSent from my iPhoneOn Dec 15, 2023, at 4:14 PM, Surajit Mondal ***@***.***> wrote:﻿
It seems that there is a factor of 4 difference between the fast and slow visibility. I have confirmed this using a test-vector test as well. While the predicted visibilities match exactly with the observed ones in case of slow visibilities, the observed fast visibilities were a factor of 4 higher than the predicted ones. The easiest way to explain this factor of 4 is the fact that the number of channels are different between fast and slow vis by exactly factor of 4. The observed fast and slow vis plots will clearly show that the range of slow visibilities is smaller than that for the fast visibilities. Now since this is a constant factor, this can be corrected by combining this in the bandpass calibration step. @binchensun @dgary50 What do you think? Should we bring this up or shall we correct for this in the bandpass correction for fast vis?
fast_vis_full.png (view on web)
slow_vis_full.png (view on web)

**Comment by binchensun** [comment]
I agree.
